import Head from 'next/head'
import { useRouter } from 'next/router'
import { useLayoutEffect } from 'react';

export default function Home() {
  
  const router = useRouter();

  useLayoutEffect(() => {
    router.push('/settings');
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}